"""Add is_mandatory and analysis_version to skill_gaps

Revision ID: 2120f53438c8
Revises: 84f38cb5e94c
Create Date: 2026-09-13 22:45:47.393012

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2120f53438c8'
down_revision: Union[str, Sequence[str], None] = '84f38cb5e94c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_mandatory', sa.Boolean(), nullable=False, server_default=sa.text('1')))
        batch_op.add_column(sa.Column('analysis_version', sa.String(), nullable=False, server_default=sa.text("'v1.0'")))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill_gaps', schema=None) as batch_op:
        batch_op.drop_column('analysis_version')
        batch_op.drop_column('is_mandatory')

    # ### end Alembic commands ###
